// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rggkuccuqeytkkgbjipg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZ2t1Y2N1cWV5dGtrZ2JqaXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NzYyNzcsImV4cCI6MjA1ODM1MjI3N30.Up4lHrw6NcfuvZYTdIoXHnTuGhHOBtqocdkqKSwg-wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);